
-- GERAL
#DROP_TABLE
DROP TABLE IF EXISTS ?;

-- #### DAO TB_ITENS ####

#TB_ITENS_CREATE_TABLE
CREATE TABLE IF NOT EXISTS TB_ITENS(
   id INTEGER PRIMARY KEY,
   name text NOT NULL
);

#TB_ITENS_INSERT
INSERT INTO TB_ITENS (id, name) VALUES (?, ?);

#TB_ITENS_SELECT_ALL
SELECT id, name FROM TB_ITENS;

#TB_ITENS_SELECT_BY_ID
SELECT * FROM TB_ITENS WHERE id = ?;

#TB_ITENS_DELETE_BY_ID
DELETE FROM TB_ITENS WHERE id = ?;

#TB_ITENS_UPDATE
UPDATE TB_ITENS SET name = ? WHERE id = ?;

#TB_ITENS_SELECT_MAX_ID
SELECT MAX(id) AS max_id FROM TB_ITENS